{% set version = "1.2.0dev" %}
{% set buildnumber = 1 %}

package:
    name: scikit-ipp
    version: {{ version }}

source:
    path: ..

build:
    number: {{ buildnumber }}

requirements:
    build:
      - {{ compiler('c') }}
    host:
      - cython
      - ipp
      - ipp-devel
      - ipp-include
      - numpy >=1.15
      - python
      - setuptools
    run:
      - ipp
      - intel-openmp # [not osx]
      - llvm-openmp # [osx]
      - numpy >=1.15
      - python

test:
    requires:
      - numpy
      - pytest
      - pytest-benchmark
    imports:
      - skipp
      - skipp.filters
      - skipp.morphology
      - skipp.transform
    commands:
      - pytest -vv
    source_files:
      - skipp/filters/tests/tests/
      - skipp/morphology/tests/
      - skipp/transform/tests/tests/

about:
     license: BSD-3-Clause
     license_family: BSD

extra:
     recipe-maintainers:
      - samir-nasibli
