{% set version = "1.0.0" %}
{% set buildnumber = 0 %}

package:
    name: scikit-ipp
    version: {{ version }}

source:
    path: ..

requirements:
    build:
      - {{ compiler('c') }}
    host:
      - cython
      - ipp
      - ipp-devel
      - ipp-include
      - numpy >=1.13.3
      - python
      - setuptools
    run:
      - ipp
      - numpy >=1.13.3
      - python

test:
    requires:
      - numpy
      - pytest
      - pytest-benchmark
      - scikit-image
      - scipy
    imports:
      - skipp
      - skipp.filters
      - skipp.morphology
      - skipp.transform
    commands:
      - pytest -vv
    source_files:
      - skipp/filters/tests/
      - skipp/morphology/tests/
      - skipp/transform/tests/

about:
     license: BSD-3-Clause
     license_family: BSD

extra:
     recipe-maintainers:
      - samir-nasibli
